import {THREE,cubeAnchor,targets,aimWorld,installRoot,resetCube,launch,runtime} from './game.js';
const state=document.querySelector('#state'),msg=document.querySelector('#msg'),codeEl=document.querySelector('#code');let lastPrompt='';
function worldFor(root){return {get forward(){return aimWorld().clone().applyQuaternion(root.getWorldQuaternion(new THREE.Quaternion()).invert()).normalize()},get forwardWorld(){return aimWorld().clone()},targets,targetPosition(id){const t=targets[Number(id)|0];return t?root.worldToLocal(t.getWorldPosition(new THREE.Vector3())):null},hit(id,a=10){const t=targets[Number(id)|0];if(!t)return false;t.userData.hp=Math.max(0,t.userData.hp-a);if(t.userData.hp<=0)t.visible=false;return true}}}
function clean(c){return String(c).replace(/^```(?:javascript|js)?\s*/i,'').replace(/```\s*$/,'').trim()}
function bad(c){if(/\bworld\s*\.\s*add\s*\(/.test(c))return'world.add invalid; use root.add';if(/\bscene\s*\.|\brenderer\s*\.|\bcamera\s*\.|setAnimationLoop\s*\(|requestAnimationFrame\s*\(/.test(c))return'host rendering APIs are unavailable; use root.add and update(dt,time)';return null}
function compile(c,root){const b=bad(c);if(b)throw Error('CONTRACT: '+b);return new Function('THREE','root','world',`"use strict";${c};return {onUse:typeof onUse==='function'?onUse:null,update:typeof update==='function'?update:null}`)(THREE,root,worldFor(root))}
function validate(c){const r=new THREE.Group();cubeAnchor.add(r);try{compile(c,r);if(!r.children.length)throw Error('CONTRACT: object must be attached with root.add(...)')}finally{cubeAnchor.remove(r)}}
const SYS=`Return ONLY executable JavaScript BODY. THREE, root, world exist. root IS the physical Cube in the player's hand. Create the requested visible object immediately at local origin and attach it using root.add(object). NEVER use world.add, scene, renderer, camera, setAnimationLoop, requestAnimationFrame. world is data only. Animation must be top-level function update(dt,time){}. Three.js is r180; particles use THREE.Points. Only define top-level onUse() for an explicitly requested special action; otherwise host ACTION launches the held object.`;
async function ask(k,m,messages){const r=await fetch('https://api.opentyphoon.ai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+k},body:JSON.stringify({model:m,messages,temperature:.08,max_tokens:5000})});if(!r.ok)throw Error('API '+r.status);return clean((await r.json()).choices?.[0]?.message?.content||'')}
function explicit(s){return /(เมื่อ|พอกด|กดใช้|เดิน|ยิง|พุ่ง|ตาม|โจมตี|ระเบิด|บิน|when used|shoot|attack|follow)/i.test(s)}
document.querySelector('#clear').onclick=resetCube;document.querySelector('#form').onsubmit=async e=>{e.preventDefault();const k=document.querySelector('#key').value.trim(),m=document.querySelector('#model').value.trim(),p=document.querySelector('#prompt').value.trim();if(!k||!p)return;lastPrompt=p;state.textContent='THINKING';try{let c=await ask(k,m,[{role:'system',content:SYS},{role:'user',content:p}]);codeEl.textContent=c;let err;for(let i=0;i<3;i++){try{validate(c);err=null;break}catch(x){err=x;if(i===2)break;state.textContent='REPAIR '+(i+1);c=await ask(k,m,[{role:'system',content:SYS},{role:'user',content:p},{role:'assistant',content:c},{role:'user',content:`Fix complete code. ${x.message}. MUST root.add the object. Never world.add/scene/renderer/camera.`}]);codeEl.textContent=c}}if(err)throw err;const r=new THREE.Group();cubeAnchor.add(r);const hooks=compile(c,r);installRoot(r,hooks);state.textContent='READY';msg.textContent='ถือ Cube-object แล้ว • ACTION พร้อม'}catch(x){state.textContent='ERROR';msg.textContent=x.message}};
function use(){try{if(explicit(lastPrompt)&&runtime.hooks.onUse)runtime.hooks.onUse();else launch();msg.textContent=runtime.launched?'ACTION • ยิงจาก Cube':'ACTION'}catch(x){state.textContent='ACTION ERROR';msg.textContent=x.message}}const A=document.querySelector('#action');A.addEventListener('touchstart',e=>{e.preventDefault();e.stopPropagation();use()},{passive:false});A.addEventListener('click',use);