import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
export {THREE};
export const scene=new THREE.Scene(); scene.background=new THREE.Color(0x070a11); scene.fog=new THREE.Fog(0x070a11,20,65);
export const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);
export const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); document.querySelector('#game').append(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbad4ff,0x151b12,2)); const sun=new THREE.DirectionalLight(0xffffff,2); sun.position.set(7,12,6); scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(70,70),new THREE.MeshStandardMaterial({color:0x18212d})); floor.rotation.x=-Math.PI/2; scene.add(floor,new THREE.GridHelper(70,70,0x42506a,0x283245));
export const player=new THREE.Group(); scene.add(player); const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.1,5,10),new THREE.MeshStandardMaterial({color:0x456fff})); body.position.y=1.05; player.add(body); const head=new THREE.Mesh(new THREE.SphereGeometry(.35,16,12),new THREE.MeshStandardMaterial({color:0xd8a985})); head.position.y=2.05; player.add(head);
export const cubeAnchor=new THREE.Group(); cubeAnchor.position.set(.82,1.45,-.35); player.add(cubeAnchor); export const baseCube=new THREE.Mesh(new THREE.BoxGeometry(.42,.42,.42),new THREE.MeshStandardMaterial({color:0x8557ff,emissive:0x351080,emissiveIntensity:2})); cubeAnchor.add(baseCube);
export const targets=[]; for(const p of [[0,1,-10],[-5,1,-14],[5,1,-16]]){const m=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.2,4,8),new THREE.MeshStandardMaterial({color:0xd92d45,emissive:0x420008}));m.position.set(...p);m.userData.hp=100;m.userData.id=targets.length;scene.add(m);targets.push(m)}
export const control={yaw:0,pitch:.38,moveX:0,moveY:0}; export const runtime={root:new THREE.Group(),hooks:{},transformed:false,launched:false,velocity:new THREE.Vector3(),time:0}; cubeAnchor.add(runtime.root);
export function aimWorld(){return new THREE.Vector3(-Math.sin(control.yaw)*Math.cos(control.pitch),Math.sin(control.pitch),-Math.cos(control.yaw)*Math.cos(control.pitch)).normalize()}
export function resetCube(){runtime.root.parent?.remove(runtime.root);runtime.root=new THREE.Group();cubeAnchor.add(runtime.root);baseCube.visible=true;runtime.hooks={};runtime.transformed=false;runtime.launched=false;runtime.velocity.set(0,0,0);runtime.time=0}
export function installRoot(root,hooks){runtime.root.parent?.remove(runtime.root);runtime.root=root;root.position.set(0,0,0);root.quaternion.identity();baseCube.visible=false;runtime.hooks=hooks;runtime.transformed=true;runtime.launched=false;runtime.time=0}
export function launch(){if(!runtime.transformed||runtime.launched)return false;cubeAnchor.updateMatrixWorld(true);runtime.root.updateMatrixWorld(true);const p=runtime.root.getWorldPosition(new THREE.Vector3()),q=runtime.root.getWorldQuaternion(new THREE.Quaternion()),s=runtime.root.getWorldScale(new THREE.Vector3());runtime.root.parent?.remove(runtime.root);scene.add(runtime.root);runtime.root.position.copy(p);runtime.root.quaternion.copy(q);runtime.root.scale.copy(s);runtime.velocity.copy(aimWorld()).multiplyScalar(9);runtime.launched=true;return true}
const clock=new THREE.Clock(); function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);runtime.time+=dt;const fw=new THREE.Vector3(-Math.sin(control.yaw),0,-Math.cos(control.yaw)),rt=new THREE.Vector3(Math.cos(control.yaw),0,-Math.sin(control.yaw));player.position.addScaledVector(fw,-control.moveY*3.5*dt).addScaledVector(rt,control.moveX*3.5*dt);player.rotation.y=control.yaw;cubeAnchor.rotation.x=-control.pitch*.55;if(runtime.hooks.update)try{runtime.hooks.update(dt,runtime.time)}catch(e){runtime.hooks.update=null;document.querySelector('#state').textContent='ANIMATION ERROR';document.querySelector('#msg').textContent=e.message}if(runtime.launched)runtime.root.position.addScaledVector(runtime.velocity,dt);const dist=9,cp=Math.cos(.38);camera.position.set(player.position.x+Math.sin(control.yaw)*cp*dist,player.position.y+2+Math.sin(.38)*dist,player.position.z+Math.cos(control.yaw)*cp*dist);camera.lookAt(player.position.x+aimWorld().x*3,1.3+aimWorld().y*2,player.position.z+aimWorld().z*3);if(!runtime.transformed){baseCube.rotation.x+=dt;baseCube.rotation.y+=dt*1.5}renderer.render(scene,camera)} frame(); addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});